#!/bin/sh

TARGET_PAGE=$1

echo "**This is a Feature Request**

<!-- Please only use this template for submitting feature/enhancement requests -->
<!-- See https://kubernetes.io/docs/contribute/start/ for guidance on writing an actionable issue description. -->

**What would you like to be added**
<!-- Describe as precisely as possible how this feature/enhancement should work from the user perspective. What should be changed, etc. -->
replace links to \`${TARGET_PAGE}\` with \`/ja${TARGET_PAGE}\`.

**Why is this needed**
\`${TARGET_PAGE}\` has already been translated into Japanese.

**Comments**
<!-- Any additional related comments that might help. Drawings/mockups would be extremely helpful (if required). -->
/language ja
/kind cleanup
/assign

lines to update
\`\`\`
$(git grep $TARGET_PAGE content/ja/docs/ | grep -v "/ja$TARGET_PAGE")
\`\`\`
base branch: dev-1.19-ja.2
"
